### ISSUE TITLE
Error loading board file: Invalid net ID

### ISSUE THREAD

**Issue by vicktorhu** [jeroen94704/klepcbgen#3]
![image](https://user-images.githubusercontent.com/9425865/87252266-c6a68c00-c49b-11ea-9e29-fcc6892575cd.png)

JSON and kicad generated files are attached below.

[V79.zip](https://github.com/jeroen94704/klepcbgen/files/4908900/V79.zip)

Thank you!

**Comment by jeroen94704** [comment]
duplicate of #4 , which is still open. I'll get around to this eventually :)

**Comment by jeroen94704** [comment]
duplicate of #4

**Comment by jeroen94704** [comment]
Thanks for attaching a json file that reproduced the issue. This should be fixed now.
