### ISSUE TITLE
error invalid net id

### ISSUE THREAD

**Issue by pre10c** [jeroen94704/klepcbgen#4]
getting this error when i try to open the pcb file

![image](https://user-images.githubusercontent.com/36589109/89735264-8a962500-da61-11ea-9e03-9ce7f89fa5bb.png)

**Comment by ohchiko** [comment]
I got this exact same issue too.

**How to reproduce:**

1. Get the keyboard layout as JSON file from [KLE](http://keyboard-layout-editor.com)
2. Execute the `klepcbgen.py` from MSYS2 (`python klepcbgen.py keyboard.json keyboard`)
3. Open the `keyboard.kicad_pcb` file
4. Error, said: _Error loading board file... Invalid net ID in..._

**Specs:**

- Windows 10 Ver. 1903
- MSYS2 Terminal mintty 3.1.4 (x86_64-pc-msys)
- Python 3.8.2
- KiCad 5.1.6

**Comment by MarkuBu** [comment]
Same on Ubuntu 20.04 and Kicad 5.1.7

**Comment by CapnJames95** [comment]
Same issue here, Windows 10 20H2 KiCad 5.1.4

**Comment by lukelex** [comment]
Same on Manjaro 5.9.16-1 with KiCad 5.1.9

**Comment by jeroen94704** [comment]
The above change hopefully fixes this issue for everybody. Please let me know if you still experience this, including the kle json that produced the error.
